#### Домашнее задание «Библиотека numpy. Вычислительные задачи»


#### Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).



In [10]:
import numpy as np

x = np.arange(9, 0, -1)
print(x, type(x))

[9 8 7 6 5 4 3 2 1] <class 'numpy.ndarray'>


#### Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.



In [18]:
def diag_matrica (n):
    matrica = np.diag(np.arange(n, -1, -1), k=0)
    print(matrica)
    print('Diagonal (sum): ', np.trace(matrica))
    print('Diagonal (elements): ', np.diagonal(matrica))
    
diag_matrica(7)    

[[7 0 0 0 0 0 0 0]
 [0 6 0 0 0 0 0 0]
 [0 0 5 0 0 0 0 0]
 [0 0 0 4 0 0 0 0]
 [0 0 0 0 3 0 0 0]
 [0 0 0 0 0 2 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0]]
Diagonal (sum):  28
Diagonal (elements):  [7 6 5 4 3 2 1 0]


#### Задание 3
Решите систему уравнений:

4x + 2y + z = 4

x + 3y = 12

5y + 4z = -3



In [23]:
from numpy import linalg

# коэффициенты при переменных в левой части уравнения
a = np.array( [ [4, 2, 1], [1, 3, 0], [0, 5, 4] ] )
# значения в правой части уравнения
b = np.array( [4, 12, -3] )
print(linalg.solve(a, b))

# проверка верности
np.allclose( np.dot(a, linalg.solve(a, b)), b )

[ 0.46666667  3.84444444 -5.55555556]


True

#### Задание 4
В материалах занятия раздел “Задача 4 домашнего задания”

Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя. Остальные столбцы - количество покупок категорий товаров этим пользователем:

Матрица в виде numpy array


users_stats = np.array(

    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

На сайт заходит очередной посетитель, о покупках которого известно следующее:

next_user_stats = np.array([0, 1, 2, 0, 0, 0])
Найдите самого похожего пользователя. Т. е. посчитайте косинусное сходство между этим пользователем и всеми пользователями из массива user_stats

In [43]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

def cosine( a, b ):
    """
    Подсчет косинуса угла между векторами a, b по их координатам
    """    
    # длины векторов
    aLength = np.linalg.norm( a )
    bLength = np.linalg.norm( b )    
    return np.dot( a, b ) / ( aLength * bLength )


#max_cos = max( [ cosine( stat, next_user_stats ) for stat in users_stats ])
#print(max_cos )

max_cos = 0
for stat in users_stats:
    cos_ = cosine( stat, next_user_stats )
    if max_cos <= cos_:
        max_cos = cos_
        max_stat = stat
        
print('самый похожий пользователь', max_stat, 'max_cos = ', max_cos)        

самый похожий пользователь [0 1 1 0 0 0] max_cos =  0.9486832980505138
